### ISSUE TITLE
Change name of repository

### ISSUE THREAD

**Issue by w0www** [danielanguita/redmine_inventory_manager#22]
Hello @danielanguita 

¿can you change the name to "redmine_inventory_manager"? 

Thanks mate!

**Comment by danielanguita** [comment]
you want to change the repository name?
from Redmine-Inventory-Manager to redmine_inventory_manager?

**Comment by w0www** [comment]
yes, then with git clone and bundle and redmine plugins install its done not its necessary move the plugin from Redmine-Inventory-Manager to redmine_inventory_manager

**Comment by danielanguita** [comment]
ok
